# ── NUST Faculty Knowledge Base ────────────────────────────
# Source: RateDeezNUST community reviews
# Only professors with 5+ reviews included for reliability
# Rating interpretation: 4.0+ Great, 3.0-3.9 Average, 2.0-2.9 Mixed, below 2.0 Tough

FACULTY_DB = {
    # ── SEECS ───────────────────────────────────────────────
    "jaudat mamoon": {
        "name": "Jaudat Mamoon",
        "school": "SEECS",
        "rating": 3.7,
        "reviews": 44,
        "summary": "One of the most reviewed SEECS professors. Students generally find him knowledgeable and approachable, but he has a reputation for strict deadlines — not a single day of delay is tolerated. He tends to favor students who are consistently engaged and present in class. Relative grading can work in your favor if you stay ahead of the curve.",
        "tips": [
            "Never miss a deadline — not even by an hour. Submit early.",
            "Class participation matters to him. Be present and engaged.",
            "He rewards consistency over last-minute cramming.",
            "Build a good rapport early in the semester — he remembers faces.",
            "Past papers from seniors are essential for his courses.",
            "If you're struggling, approach him during office hours — he responds well to proactive students.",
        ],
        "teaching_style": "Structured and disciplined. Expects students to keep up with the pace.",
        "difficulty": "Medium-High",
        "courses": ["OOP", "CS core courses"],
    },
    "ammar ahmed": {
        "name": "Ammar Ahmed",
        "school": "SEECS",
        "rating": 4.7,
        "reviews": 43,
        "summary": "One of the highest rated professors at SEECS with 43 reviews. Students love his teaching style — clear, engaging, and genuinely helpful. Highly recommended for any course he teaches.",
        "tips": [
            "Attend every class — his lectures are genuinely worth it.",
            "He explains concepts clearly — ask questions freely.",
            "One of the best options if you get to choose sections.",
        ],
        "teaching_style": "Engaging, clear, student-friendly.",
        "difficulty": "Medium",
        "courses": ["Various CS courses"],
    },
    "imran malik": {
        "name": "Imran Malik",
        "school": "SEECS",
        "rating": 4.7,
        "reviews": 29,
        "summary": "Highly rated with 29 reviews. Students consistently praise his teaching. Strong recommendation from the student community.",
        "tips": [
            "Attend regularly — his teaching style rewards consistent students.",
            "Approachable for questions and office hours.",
        ],
        "teaching_style": "Clear and student-oriented.",
        "difficulty": "Medium",
        "courses": ["Various CS courses"],
    },
    "saira zainab": {
        "name": "Saira Zainab",
        "school": "SEECS",
        "rating": 4.5,
        "reviews": 31,
        "summary": "Highly rated with 31 reviews — one of the most reviewed and well-rated professors at SEECS. Students find her teaching effective and fair.",
        "tips": [
            "Very approachable. Don't hesitate to ask for help.",
            "Fair grading relative to effort put in.",
            "Strong recommendation from students across batches.",
        ],
        "teaching_style": "Effective and fair.",
        "difficulty": "Medium",
        "courses": ["Various courses"],
    },
    "maajid maqbool": {
        "name": "Maajid Maqbool",
        "school": "SEECS",
        "rating": 4.8,
        "reviews": 20,
        "summary": "Exceptional rating of 4.8 with 20 reviews. One of the best professors at SEECS according to students. Highly recommended.",
        "tips": [
            "Take any course he offers if you get the chance.",
            "Students consistently rate him as engaging and fair.",
        ],
        "teaching_style": "Excellent — highly engaging.",
        "difficulty": "Medium",
        "courses": ["Various CS courses"],
    },
    "rai sajjad saif": {
        "name": "Rai Sajjad Saif",
        "school": "SEECS",
        "rating": 4.2,
        "reviews": 24,
        "summary": "Good rating with 24 reviews. Students generally have positive experiences. Reliable choice.",
        "tips": [
            "Consistent teaching style — students know what to expect.",
            "Good for students who prefer structured courses.",
        ],
        "teaching_style": "Structured and consistent.",
        "difficulty": "Medium",
        "courses": ["Various courses"],
    },
    "syed muhammad ali musa": {
        "name": "Syed Muhammad Ali Musa",
        "school": "SEECS",
        "rating": 4.4,
        "reviews": 25,
        "summary": "Highly rated with 25 reviews. Students find him effective and helpful. Strong positive sentiment.",
        "tips": [
            "Approachable and genuinely helpful to students.",
            "Good teaching style — recommended.",
        ],
        "teaching_style": "Helpful and clear.",
        "difficulty": "Medium",
        "courses": ["Various courses"],
    },
    "nadeem nawaz khan": {
        "name": "Nadeem Nawaz Khan",
        "school": "SEECS",
        "rating": 4.5,
        "reviews": 15,
        "summary": "Very well rated with 15 reviews. Students appreciate his teaching approach.",
        "tips": [
            "Good professor to have — students rate him highly.",
            "Fair in grading and approachable.",
        ],
        "teaching_style": "Student-friendly.",
        "difficulty": "Medium",
        "courses": ["Various courses"],
    },
    "faisal shafait": {
        "name": "Faisal Shafait",
        "school": "SEECS",
        "rating": 4.4,
        "reviews": 16,
        "summary": "Well rated researcher and professor. Known for high-quality teaching, especially in AI/ML related areas.",
        "tips": [
            "Excellent for AI/ML courses.",
            "Research-focused — great if you want to get into research.",
            "Come prepared — he teaches at a high level.",
        ],
        "teaching_style": "Research-oriented, high quality.",
        "difficulty": "Medium-High",
        "courses": ["AI", "ML", "Computer Vision"],
    },
    "hina yousaf": {
        "name": "Hina Yousaf",
        "school": "SEECS",
        "rating": 4.4,
        "reviews": 16,
        "summary": "Very well rated. Students consistently have positive experiences.",
        "tips": [
            "Approachable and fair.",
            "Students recommend her courses.",
        ],
        "teaching_style": "Clear and approachable.",
        "difficulty": "Medium",
        "courses": ["Various courses"],
    },
    "arshad nazir": {
        "name": "Arshad Nazir",
        "school": "SEECS",
        "rating": 3.4,
        "reviews": 18,
        "summary": "Average rating with 18 reviews. Mixed feedback — some students find him okay, others find the course challenging. Known for DLD and digital systems courses.",
        "tips": [
            "Pay close attention to lab work — it matters.",
            "Attend regularly and keep up with assignments.",
            "Past papers are very helpful for his courses.",
        ],
        "teaching_style": "Technical and detail-oriented.",
        "difficulty": "Medium-High",
        "courses": ["DLD", "Digital Systems"],
    },
    "junaid younas": {
        "name": "Junaid Younas",
        "school": "SEECS",
        "rating": 2.2,
        "reviews": 25,
        "summary": "Below average rating with 25 reviews — significant student feedback. Many students find his courses difficult to navigate. Approach with preparation.",
        "tips": [
            "Form a strong study group for his courses.",
            "Past papers are essential — get them from seniors.",
            "Attend all classes — missing any can hurt significantly.",
            "Be very proactive about seeking help early.",
        ],
        "teaching_style": "Strict and demanding.",
        "difficulty": "High",
        "courses": ["Various courses"],
    },
    "iram tariq bhatti": {
        "name": "Iram Tariq Bhatti",
        "school": "SEECS",
        "rating": 2.7,
        "reviews": 15,
        "summary": "Mixed reviews with 15 responses. Students have varied experiences.",
        "tips": [
            "Stay on top of assignments from day one.",
            "Clarify grading criteria early in the semester.",
        ],
        "teaching_style": "Demanding.",
        "difficulty": "Medium-High",
        "courses": ["Various courses"],
    },
    "madiha khalid": {
        "name": "Madiha Khalid",
        "school": "SEECS",
        "rating": 2.8,
        "reviews": 18,
        "summary": "Mixed reviews with 18 responses. Students have varying experiences.",
        "tips": [
            "Keep up with course material consistently.",
            "Form study groups early.",
        ],
        "teaching_style": "Mixed feedback.",
        "difficulty": "Medium-High",
        "courses": ["Various courses"],
    },
    "muhammad sohail iqbal": {
        "name": "Muhammad Sohail Iqbal",
        "school": "SEECS",
        "rating": 2.9,
        "reviews": 20,
        "summary": "Average rating with 20 reviews. Mixed student experiences.",
        "tips": [
            "Clarify expectations early.",
            "Stay consistent with submissions.",
        ],
        "teaching_style": "Mixed.",
        "difficulty": "Medium",
        "courses": ["Various courses"],
    },
    "gibrail islam": {
        "name": "Gibrail Islam",
        "school": "SEECS",
        "rating": 3.1,
        "reviews": 21,
        "summary": "Average rating with 21 reviews. Students have mixed but mostly neutral experiences.",
        "tips": [
            "Keep pace with the course from week one.",
            "Ask questions — he responds to engaged students.",
        ],
        "teaching_style": "Average.",
        "difficulty": "Medium",
        "courses": ["Various courses"],
    },
    "taufique ur rehman": {
        "name": "Taufique Ur Rehman",
        "school": "SEECS",
        "rating": 3.1,
        "reviews": 16,
        "summary": "Average rating with 16 reviews.",
        "tips": [
            "Stay consistent throughout the semester.",
        ],
        "teaching_style": "Average.",
        "difficulty": "Medium",
        "courses": ["Various courses"],
    },
    "quanita kiran": {
        "name": "Quanita Kiran",
        "school": "SEECS",
        "rating": 3.6,
        "reviews": 17,
        "summary": "Above average rating with 17 reviews. Students generally have decent experiences.",
        "tips": [
            "Consistent effort pays off in her courses.",
        ],
        "teaching_style": "Decent.",
        "difficulty": "Medium",
        "courses": ["Various courses"],
    },
    "saeed afzal": {
        "name": "Saeed Afzal",
        "school": "SEECS",
        "rating": 3.6,
        "reviews": 21,
        "summary": "Above average rating with 21 reviews. Reliable professor with mostly positive feedback.",
        "tips": [
            "Good professor overall — stay engaged.",
            "Assignments taken seriously.",
        ],
        "teaching_style": "Reliable.",
        "difficulty": "Medium",
        "courses": ["Various courses"],
    },
    "khursheed muhammad": {
        "name": "Khursheed Muhammad",
        "school": "SEECS",
        "rating": 3.6,
        "reviews": 22,
        "summary": "Above average rating with 22 reviews — one of the more reviewed professors. Generally positive student experience.",
        "tips": [
            "Good professor to have. Stay on top of coursework.",
            "Fair in grading.",
        ],
        "teaching_style": "Fair and organized.",
        "difficulty": "Medium",
        "courses": ["Various courses"],
    },
    "sidra shafiq": {
        "name": "Sidra Shafiq",
        "school": "SEECS",
        "rating": 3.7,
        "reviews": 18,
        "summary": "Good rating with 18 reviews. Positive student experiences overall.",
        "tips": [
            "Approachable and fair.",
            "Good choice for electives if available.",
        ],
        "teaching_style": "Good.",
        "difficulty": "Medium",
        "courses": ["Various courses"],
    },
    "ansar shahzadi": {
        "name": "Ansar Shahzadi",
        "school": "SEECS",
        "rating": 4.3,
        "reviews": 18,
        "summary": "Very well rated with 18 reviews. Strong positive student feedback.",
        "tips": [
            "Highly recommended. Take her courses if you can.",
            "Fair grading and good teaching.",
        ],
        "teaching_style": "Excellent.",
        "difficulty": "Medium",
        "courses": ["Various courses"],
    },
    "hafiz syed muhammad bilal ali": {
        "name": "Hafiz Syed Muhammad Bilal Ali",
        "school": "SEECS",
        "rating": 4.1,
        "reviews": 14,
        "summary": "Good rating with 14 reviews. Students generally happy.",
        "tips": [
            "Good professor — attend regularly.",
        ],
        "teaching_style": "Good.",
        "difficulty": "Medium",
        "courses": ["Various courses"],
    },
    "atifa kanwal": {
        "name": "Atifa Kanwal",
        "school": "SEECS",
        "rating": 3.1,
        "reviews": 16,
        "summary": "Average rating with 16 reviews.",
        "tips": [
            "Stay consistent and keep up with coursework.",
        ],
        "teaching_style": "Average.",
        "difficulty": "Medium",
        "courses": ["Various courses"],
    },
    "adnan aslam": {
        "name": "Adnan Aslam",
        "school": "SEECS",
        "rating": 3.9,
        "reviews": 13,
        "summary": "Good rating with 13 reviews. Positive student experiences.",
        "tips": [
            "Good professor overall.",
            "Engaging lectures.",
        ],
        "teaching_style": "Engaging.",
        "difficulty": "Medium",
        "courses": ["Various courses"],
    },
    "ayesha habib": {
        "name": "Ayesha Habib",
        "school": "SEECS",
        "rating": 2.6,
        "reviews": 13,
        "summary": "Below average rating with 13 reviews. Students find her courses challenging.",
        "tips": [
            "Prepare thoroughly from the start.",
            "Form study groups early.",
            "Get past papers from seniors.",
        ],
        "teaching_style": "Demanding.",
        "difficulty": "High",
        "courses": ["Various courses"],
    },
    "neelma naz": {
        "name": "Neelma Naz",
        "school": "SEECS",
        "rating": 2.3,
        "reviews": 10,
        "summary": "Below average rating. Students find her courses tough.",
        "tips": [
            "Stay on top of assignments from day one.",
            "Past papers essential.",
        ],
        "teaching_style": "Strict.",
        "difficulty": "High",
        "courses": ["Various courses"],
    },
    "shah khalid": {
        "name": "Shah Khalid",
        "school": "SEECS",
        "rating": 2.2,
        "reviews": 12,
        "summary": "Below average rating with 12 reviews. Mixed to negative student feedback.",
        "tips": [
            "Be very proactive — don't fall behind.",
            "Seek help from seniors who've taken his courses.",
        ],
        "teaching_style": "Tough.",
        "difficulty": "High",
        "courses": ["Various courses"],
    },
    "mehwish fatima": {
        "name": "Mehwish Fatima",
        "school": "SEECS",
        "rating": 1.8,
        "reviews": 18,
        "summary": "Low rating with 18 reviews — significant consistent feedback. Students find her courses very difficult to navigate. Prepare extra hard.",
        "tips": [
            "Get past papers from multiple batches of seniors.",
            "Form a strong study group immediately.",
            "Visit during office hours early — don't wait until exam season.",
            "Clarify grading criteria in week one.",
        ],
        "teaching_style": "Very demanding.",
        "difficulty": "Very High",
        "courses": ["Various courses"],
    },
    "sidra sultana": {
        "name": "Sidra Sultana",
        "school": "SEECS",
        "rating": 1.6,
        "reviews": 18,
        "summary": "Low rating with 18 reviews. Consistent negative feedback from students. Approach with maximum preparation.",
        "tips": [
            "Take this course very seriously from day one.",
            "Study group is not optional — form one immediately.",
            "Past papers are essential.",
            "Never miss a class.",
        ],
        "teaching_style": "Very strict.",
        "difficulty": "Very High",
        "courses": ["Various courses"],
    },
    "moeed ahmed": {
        "name": "Moeed Ahmed",
        "school": "SEECS",
        "rating": 1.7,
        "reviews": 15,
        "summary": "Low rating with 15 reviews. Students consistently find his courses very challenging.",
        "tips": [
            "Extra preparation required.",
            "Get seniors' notes and past papers.",
            "Start assignments early — don't leave anything for last minute.",
        ],
        "teaching_style": "Very demanding.",
        "difficulty": "Very High",
        "courses": ["Various courses"],
    },
    "muhammad ahmad rathore": {
        "name": "Muhammad Ahmad Rathore",
        "school": "SEECS",
        "rating": 1.9,
        "reviews": 14,
        "summary": "Low rating with 14 reviews. Students find courses difficult.",
        "tips": [
            "Prepare thoroughly from semester start.",
            "Past papers essential.",
        ],
        "teaching_style": "Tough.",
        "difficulty": "High",
        "courses": ["Various courses"],
    },
    "hafiz arslan ramzan": {
        "name": "Hafiz Arslan Ramzan",
        "school": "SEECS",
        "rating": 1.6,
        "reviews": 10,
        "summary": "Low rating with 10 reviews.",
        "tips": [
            "Be very prepared.",
            "Use senior resources extensively.",
        ],
        "teaching_style": "Difficult.",
        "difficulty": "Very High",
        "courses": ["Various courses"],
    },
    "habeel ahmad": {
        "name": "Habeel Ahmad",
        "school": "SEECS",
        "rating": 2.5,
        "reviews": 13,
        "summary": "Below average rating with 13 reviews. Mixed student experiences.",
        "tips": [
            "Stay consistent and don't fall behind.",
        ],
        "teaching_style": "Mixed.",
        "difficulty": "Medium-High",
        "courses": ["Various courses"],
    },
    "sobia jamil": {
        "name": "Sobia Jamil",
        "school": "SEECS",
        "rating": 3.2,
        "reviews": 14,
        "summary": "Average rating with 14 reviews.",
        "tips": [
            "Consistent effort pays off.",
        ],
        "teaching_style": "Average.",
        "difficulty": "Medium",
        "courses": ["Various courses"],
    },
    "mughees ahmed": {
        "name": "Mughees Ahmed",
        "school": "SEECS",
        "rating": 3.1,
        "reviews": 14,
        "summary": "Average rating with 14 reviews.",
        "tips": ["Stay on top of coursework."],
        "teaching_style": "Average.",
        "difficulty": "Medium",
        "courses": ["Various courses"],
    },
    "neelma riaz": {
        "name": "Neelma Riaz",
        "school": "SEECS",
        "rating": 3.2,
        "reviews": 13,
        "summary": "Average rating with 13 reviews.",
        "tips": ["Consistent attendance and submissions."],
        "teaching_style": "Average.",
        "difficulty": "Medium",
        "courses": ["Various courses"],
    },
    "hina munir dutt": {
        "name": "Hina Munir Dutt",
        "school": "SEECS",
        "rating": 2.5,
        "reviews": 10,
        "summary": "Below average rating with 10 reviews.",
        "tips": ["Extra preparation needed.", "Get senior resources."],
        "teaching_style": "Demanding.",
        "difficulty": "High",
        "courses": ["Various courses"],
    },
    "hashir moheed kiani": {
        "name": "Hashir Moheed Kiani",
        "school": "SEECS",
        "rating": 4.8,
        "reviews": 12,
        "summary": "Excellent rating of 4.8 with 12 reviews. Highly recommended.",
        "tips": ["Great professor — take any course he offers."],
        "teaching_style": "Excellent.",
        "difficulty": "Medium",
        "courses": ["Various courses"],
    },
    "muhammad moazam fraz": {
        "name": "Muhammad Moazam Fraz",
        "school": "SEECS",
        "rating": 4.8,
        "reviews": 8,
        "summary": "Excellent rating with strong student feedback.",
        "tips": ["Highly recommended professor."],
        "teaching_style": "Excellent.",
        "difficulty": "Medium",
        "courses": ["AI", "ML"],
    },
    "muhammad imran malik": {
        "name": "Muhammad Imran Malik",
        "school": "SEECS",
        "rating": 4.7,
        "reviews": 11,
        "summary": "Highly rated with 11 reviews. Strong positive feedback.",
        "tips": ["Great professor to have."],
        "teaching_style": "Excellent.",
        "difficulty": "Medium",
        "courses": ["Various courses"],
    },
    "sara tariq sheikh": {
        "name": "Sara Tariq Sheikh",
        "school": "SEECS",
        "rating": 5.0,
        "reviews": 11,
        "summary": "Perfect rating with 11 reviews. Exceptional professor — highest rated at SEECS.",
        "tips": ["Take any course she offers. Students universally love her.", "Very approachable and genuinely helpful."],
        "teaching_style": "Exceptional.",
        "difficulty": "Medium",
        "courses": ["Various courses"],
    },
    "aftab farooq": {
        "name": "Aftab Farooq",
        "school": "SEECS",
        "rating": 4.7,
        "reviews": 11,
        "summary": "Highly rated with very positive student feedback.",
        "tips": ["Recommended professor."],
        "teaching_style": "Excellent.",
        "difficulty": "Medium",
        "courses": ["Various courses"],
    },
    "areeba rameen": {
        "name": "Areeba Rameen",
        "school": "SEECS",
        "rating": 4.4,
        "reviews": 9,
        "summary": "Well rated with positive student feedback.",
        "tips": ["Good professor — recommended."],
        "teaching_style": "Good.",
        "difficulty": "Medium",
        "courses": ["Various courses"],
    },
    "naema asif": {
        "name": "Naema Asif",
        "school": "SEECS",
        "rating": 3.8,
        "reviews": 6,
        "summary": "Good rating with decent student feedback.",
        "tips": ["Decent professor overall."],
        "teaching_style": "Good.",
        "difficulty": "Medium",
        "courses": ["Various courses"],
    },
    "ayesha hakim": {
        "name": "Ayesha Hakim",
        "school": "SEECS",
        "rating": 3.8,
        "reviews": 4,
        "summary": "Good rating.",
        "tips": ["Decent professor."],
        "teaching_style": "Good.",
        "difficulty": "Medium",
        "courses": ["Various courses"],
    },
    "ehsan ul hassan": {
        "name": "Ehsan Ul Hassan",
        "school": "SEECS",
        "rating": 3.7,
        "reviews": 12,
        "summary": "Good rating with 12 reviews. Generally positive student experiences.",
        "tips": ["Good professor overall."],
        "teaching_style": "Good.",
        "difficulty": "Medium",
        "courses": ["Various courses"],
    },
    "urooj akmal": {
        "name": "Urooj Akmal",
        "school": "SEECS",
        "rating": 3.3,
        "reviews": 13,
        "summary": "Average rating with 13 reviews.",
        "tips": ["Consistent effort required."],
        "teaching_style": "Average.",
        "difficulty": "Medium",
        "courses": ["Various courses"],
    },
    "hirra anwar": {
        "name": "Hirra Anwar",
        "school": "SEECS",
        "rating": 3.2,
        "reviews": 11,
        "summary": "Average rating with 11 reviews.",
        "tips": ["Stay consistent throughout semester."],
        "teaching_style": "Average.",
        "difficulty": "Medium",
        "courses": ["Various courses"],
    },
    "farid gul": {
        "name": "Farid Gul",
        "school": "SEECS",
        "rating": 2.6,
        "reviews": 9,
        "summary": "Below average rating.",
        "tips": ["Extra preparation needed.", "Get past papers from seniors."],
        "teaching_style": "Demanding.",
        "difficulty": "High",
        "courses": ["Various courses"],
    },
    "zunera zahid": {
        "name": "Zunera Zahid",
        "school": "SEECS",
        "rating": 3.0,
        "reviews": 10,
        "summary": "Average rating with 10 reviews.",
        "tips": ["Keep up with coursework consistently."],
        "teaching_style": "Average.",
        "difficulty": "Medium",
        "courses": ["Various courses"],
    },
    "ayesha asif": {
        "name": "Ayesha Asif",
        "school": "SEECS",
        "rating": 2.1,
        "reviews": 11,
        "summary": "Low rating with 11 reviews. Students find courses tough.",
        "tips": ["Prepare thoroughly.", "Use study groups.", "Past papers essential."],
        "teaching_style": "Tough.",
        "difficulty": "High",
        "courses": ["Various courses"],
    },
    "ayesha kanwal": {
        "name": "Ayesha Kanwal",
        "school": "SEECS",
        "rating": 1.4,
        "reviews": 5,
        "summary": "Low rating. Students find her very difficult.",
        "tips": ["Maximum preparation required.", "Form study group immediately."],
        "teaching_style": "Very strict.",
        "difficulty": "Very High",
        "courses": ["Various courses"],
    },
    "sahar arshad": {
        "name": "Sahar Arshad",
        "school": "SEECS",
        "rating": 1.8,
        "reviews": 6,
        "summary": "Low rating. Difficult course experience reported by students.",
        "tips": ["Extra preparation from day one.", "Get senior resources."],
        "teaching_style": "Tough.",
        "difficulty": "High",
        "courses": ["Various courses"],
    },
    "mehvish rashid": {
        "name": "Mehvish Rashid",
        "school": "SEECS",
        "rating": 1.5,
        "reviews": 8,
        "summary": "Low rating with consistent negative feedback.",
        "tips": ["Prepare extensively.", "Study group essential.", "Past papers critical."],
        "teaching_style": "Very tough.",
        "difficulty": "Very High",
        "courses": ["Various courses"],
    },
    "shakeela bibi": {
        "name": "Shakeela Bibi",
        "school": "SEECS",
        "rating": 1.5,
        "reviews": 10,
        "summary": "Low rating with significant student feedback.",
        "tips": ["Extra effort required.", "Never miss class.", "Get help from seniors early."],
        "teaching_style": "Very demanding.",
        "difficulty": "Very High",
        "courses": ["Various courses"],
    },
    "muhammad ashraf": {
        "name": "Muhammad Ashraf",
        "school": "SEECS",
        "rating": 1.8,
        "reviews": 9,
        "summary": "Low rating. Students find courses difficult.",
        "tips": ["Extra preparation needed.", "Past papers essential."],
        "teaching_style": "Tough.",
        "difficulty": "High",
        "courses": ["Various courses"],
    },
    "seemab latif": {
        "name": "SEEMAB LATIF",
        "school": "SEECS",
        "rating": 2.6,
        "reviews": 8,
        "summary": "Below average rating.",
        "tips": ["Stay consistent.", "Don't fall behind."],
        "teaching_style": "Demanding.",
        "difficulty": "Medium-High",
        "courses": ["Various courses"],
    },
    "fahad ahmed satti": {
        "name": "Fahad Ahmed Satti",
        "school": "SEECS",
        "rating": 2.1,
        "reviews": 7,
        "summary": "Low rating. Students find courses tough.",
        "tips": ["Strong preparation needed.", "Study group recommended."],
        "teaching_style": "Tough.",
        "difficulty": "High",
        "courses": ["Various courses"],
    },
    "farzana jabeen": {
        "name": "Farzana Jabeen",
        "school": "SEECS",
        "rating": 2.5,
        "reviews": 8,
        "summary": "Below average rating.",
        "tips": ["Consistent effort from start.", "Get past papers."],
        "teaching_style": "Demanding.",
        "difficulty": "Medium-High",
        "courses": ["Various courses"],
    },
    "syed taha ali": {
        "name": "Syed Taha Ali",
        "school": "SEECS",
        "rating": 4.1,
        "reviews": 8,
        "summary": "Good rating with positive student feedback.",
        "tips": ["Good professor — engage actively."],
        "teaching_style": "Good.",
        "difficulty": "Medium",
        "courses": ["Various courses"],
    },
    "rabia irfan": {
        "name": "Rabia Irfan",
        "school": "SEECS",
        "rating": 3.1,
        "reviews": 7,
        "summary": "Average rating.",
        "tips": ["Consistent effort required."],
        "teaching_style": "Average.",
        "difficulty": "Medium",
        "courses": ["Various courses"],
    },
    "huma ghafoor": {
        "name": "Huma Ghafoor",
        "school": "SEECS",
        "rating": 3.1,
        "reviews": 7,
        "summary": "Average rating.",
        "tips": ["Keep up with coursework."],
        "teaching_style": "Average.",
        "difficulty": "Medium",
        "courses": ["Various courses"],
    },
    "yasir rizwan": {
        "name": "Yasir Rizwan",
        "school": "SEECS",
        "rating": 3.0,
        "reviews": 9,
        "summary": "Average rating with 9 reviews.",
        "tips": ["Consistent attendance and submissions."],
        "teaching_style": "Average.",
        "difficulty": "Medium",
        "courses": ["Various courses"],
    },
    "maria athar": {
        "name": "Maria Athar",
        "school": "SEECS",
        "rating": 4.3,
        "reviews": 11,
        "summary": "Very good rating with 11 reviews. Students have positive experiences.",
        "tips": ["Good professor — recommended."],
        "teaching_style": "Good.",
        "difficulty": "Medium",
        "courses": ["Various courses"],
    },
    "wajid mumtaz": {
        "name": "Wajid Mumtaz",
        "school": "SEECS",
        "rating": 4.3,
        "reviews": 7,
        "summary": "Good rating with positive feedback.",
        "tips": ["Good professor overall."],
        "teaching_style": "Good.",
        "difficulty": "Medium",
        "courses": ["Various courses"],
    },
    "azad akhter siddiqui": {
        "name": "Azad Akhter Siddiqui",
        "school": "SEECS",
        "rating": 4.3,
        "reviews": 7,
        "summary": "Good rating with positive student feedback.",
        "tips": ["Good professor — engage actively."],
        "teaching_style": "Good.",
        "difficulty": "Medium",
        "courses": ["Various courses"],
    },
    "nazia perwaiz": {
        "name": "Nazia Perwaiz",
        "school": "SEECS",
        "rating": 4.4,
        "reviews": 7,
        "summary": "Very good rating. Positive student experiences.",
        "tips": ["Recommended professor."],
        "teaching_style": "Good.",
        "difficulty": "Medium",
        "courses": ["Various courses"],
    },
    "maryam sajjad": {
        "name": "Maryam Sajjad",
        "school": "SEECS",
        "rating": 4.7,
        "reviews": 6,
        "summary": "Excellent rating. Students highly recommend her.",
        "tips": ["Great professor — take her courses."],
        "teaching_style": "Excellent.",
        "difficulty": "Medium",
        "courses": ["Various courses"],
    },
    "rafia ahmad": {
        "name": "Rafia Ahmad",
        "school": "SEECS",
        "rating": 4.3,
        "reviews": 6,
        "summary": "Good rating with positive feedback.",
        "tips": ["Good professor overall."],
        "teaching_style": "Good.",
        "difficulty": "Medium",
        "courses": ["Various courses"],
    },
    "samia tahir": {
        "name": "Samia Tahir",
        "school": "SEECS",
        "rating": 3.9,
        "reviews": 7,
        "summary": "Good rating with decent student experiences.",
        "tips": ["Good professor — engage actively."],
        "teaching_style": "Good.",
        "difficulty": "Medium",
        "courses": ["Various courses"],
    },
    "muhammad khuram shahzad": {
        "name": "Muhammad Khuram Shahzad",
        "school": "SEECS",
        "rating": 3.9,
        "reviews": 10,
        "summary": "Good rating with 10 reviews.",
        "tips": ["Good professor overall."],
        "teaching_style": "Good.",
        "difficulty": "Medium",
        "courses": ["Various courses"],
    },
    "muhammad saood sarwar": {
        "name": "Muhammad Saood Sarwar",
        "school": "SEECS",
        "rating": 3.4,
        "reviews": 5,
        "summary": "Average rating.",
        "tips": ["Keep consistent."],
        "teaching_style": "Average.",
        "difficulty": "Medium",
        "courses": ["Various courses"],
    },
    "zuhair zafar": {
        "name": "Zuhair Zafar",
        "school": "SEECS",
        "rating": 2.4,
        "reviews": 7,
        "summary": "Below average rating.",
        "tips": ["Extra effort required.", "Past papers helpful."],
        "teaching_style": "Tough.",
        "difficulty": "High",
        "courses": ["Various courses"],
    },
    "muhammad daud abdullah asif": {
        "name": "Muhammad Daud Abdullah Asif",
        "school": "SEECS",
        "rating": 2.0,
        "reviews": 9,
        "summary": "Low rating with consistent negative feedback.",
        "tips": ["Extra preparation needed.", "Study group essential."],
        "teaching_style": "Tough.",
        "difficulty": "High",
        "courses": ["Various courses"],
    },
    "syed tassawar hussain kazmi": {
        "name": "Syed Tassawar Hussain Kazmi",
        "school": "SEECS",
        "rating": 2.3,
        "reviews": 3,
        "summary": "Below average rating.",
        "tips": ["Prepare thoroughly."],
        "teaching_style": "Demanding.",
        "difficulty": "High",
        "courses": ["Various courses"],
    },
    "hassaan khaliq qureshi": {
        "name": "Hassaan Khaliq Qureshi",
        "school": "SEECS",
        "rating": 1.7,
        "reviews": 3,
        "summary": "Low rating.",
        "tips": ["Extra preparation needed."],
        "teaching_style": "Tough.",
        "difficulty": "High",
        "courses": ["Various courses"],
    },
    "salman abdul ghafoor": {
        "name": "Salman Abdul Ghafoor",
        "school": "SEECS",
        "rating": 3.5,
        "reviews": 6,
        "summary": "Above average rating.",
        "tips": ["Good professor — stay engaged."],
        "teaching_style": "Good.",
        "difficulty": "Medium",
        "courses": ["Various courses"],
    },
    "muhammad naseer bajwa": {
        "name": "Muhammad Naseer Bajwa",
        "school": "SEECS",
        "rating": 3.8,
        "reviews": 6,
        "summary": "Good rating with positive student feedback.",
        "tips": ["Good professor overall."],
        "teaching_style": "Good.",
        "difficulty": "Medium",
        "courses": ["Various courses"],
    },
    "muhammad jameel nawaz malik": {
        "name": "Muhammad Jameel Nawaz Malik",
        "school": "SEECS",
        "rating": 3.9,
        "reviews": 7,
        "summary": "Good rating. Positive student experiences.",
        "tips": ["Good professor — attend regularly."],
        "teaching_style": "Good.",
        "difficulty": "Medium",
        "courses": ["Various courses"],
    },
    "muhammad yousaf": {
        "name": "Muhammad Yousaf",
        "school": "SEECS",
        "rating": 3.4,
        "reviews": 11,
        "summary": "Average rating with 11 reviews.",
        "tips": ["Consistent effort pays off."],
        "teaching_style": "Average.",
        "difficulty": "Medium",
        "courses": ["Various courses"],
    },
    "ibrar hussain": {
        "name": "Ibrar Hussain",
        "school": "SEECS",
        "rating": 3.2,
        "reviews": 5,
        "summary": "Average rating.",
        "tips": ["Keep pace with coursework."],
        "teaching_style": "Average.",
        "difficulty": "Medium",
        "courses": ["Various courses"],
    },
    "syed imran ali": {
        "name": "Syed Imran Ali",
        "school": "SEECS",
        "rating": 2.8,
        "reviews": 8,
        "summary": "Below average rating.",
        "tips": ["Extra effort needed.", "Don't fall behind."],
        "teaching_style": "Demanding.",
        "difficulty": "Medium-High",
        "courses": ["Various courses"],
    },
    "momina moetesum": {
        "name": "Momina Moetesum",
        "school": "SEECS",
        "rating": 2.8,
        "reviews": 6,
        "summary": "Below average rating.",
        "tips": ["Consistent effort from start."],
        "teaching_style": "Demanding.",
        "difficulty": "Medium-High",
        "courses": ["Various courses"],
    },
    "fahd ahmad khan": {
        "name": "Fahd Ahmad Khan",
        "school": "SEECS",
        "rating": 2.0,
        "reviews": 1,
        "summary": "Limited reviews available.",
        "tips": ["Ask seniors for their experience."],
        "teaching_style": "Unknown — limited data.",
        "difficulty": "Unknown",
        "courses": ["Various courses"],
    },
}


def get_professor_info(name: str) -> dict:
    """
    Looks up a professor by name. Returns their rating, tips, and summary.
    Does fuzzy matching on name.
    """
    name_lower = name.lower().strip()

    # Direct match
    if name_lower in FACULTY_DB:
        prof = FACULTY_DB[name_lower]
        return _format_professor_response(prof)

    # Partial match — check if any key contains the search term
    matches = []
    for key, prof in FACULTY_DB.items():
        if name_lower in key or any(part in key for part in name_lower.split() if len(part) > 3):
            matches.append(prof)

    if matches:
        # Return best match (most reviews = most reliable)
        best = max(matches, key=lambda x: x["reviews"])
        return _format_professor_response(best)

    return {
        "found": False,
        "name": name,
        "message": f"No data found for '{name}' in our database. Ask seniors who've taken their courses — they'll have the most accurate intel.",
        "tip": "Check with your batch WhatsApp group or senior batches for direct feedback."
    }


def _format_professor_response(prof: dict) -> dict:
    rating = prof["rating"]
    reviews = prof["reviews"]

    # Rating interpretation
    if rating >= 4.5:
        verdict = "Excellent — highly recommended by students"
        emoji = "⭐⭐⭐⭐⭐"
    elif rating >= 4.0:
        verdict = "Very good — positive student experiences"
        emoji = "⭐⭐⭐⭐"
    elif rating >= 3.5:
        verdict = "Good — mostly positive, some mixed reviews"
        emoji = "⭐⭐⭐½"
    elif rating >= 3.0:
        verdict = "Average — mixed experiences, manageable with effort"
        emoji = "⭐⭐⭐"
    elif rating >= 2.5:
        verdict = "Below average — prepare extra hard"
        emoji = "⭐⭐½"
    elif rating >= 2.0:
        verdict = "Tough — significant student difficulty reported"
        emoji = "⭐⭐"
    else:
        verdict = "Very tough — maximum preparation required"
        emoji = "⭐"

    return {
        "found": True,
        "name": prof["name"],
        "school": prof["school"],
        "rating": f"{rating}/5.0",
        "reviews": reviews,
        "verdict": verdict,
        "emoji": emoji,
        "summary": prof["summary"],
        "survival_tips": prof["tips"],
        "teaching_style": prof["teaching_style"],
        "difficulty": prof["difficulty"],
        "courses": prof.get("courses", ["Various courses"]),
    }


def get_top_professors(school: str = "SEECS", limit: int = 5) -> list:
    """Returns top rated professors for a school."""
    school_profs = [p for p in FACULTY_DB.values() if p["school"] == school and p["reviews"] >= 5]
    sorted_profs = sorted(school_profs, key=lambda x: (x["rating"], x["reviews"]), reverse=True)
    return [_format_professor_response(p) for p in sorted_profs[:limit]]


def get_professors_to_avoid(school: str = "SEECS", threshold: float = 2.5) -> list:
    """Returns professors with low ratings — ones to be careful about."""
    school_profs = [p for p in FACULTY_DB.values() if p["school"] == school and p["rating"] < threshold and p["reviews"] >= 5]
    sorted_profs = sorted(school_profs, key=lambda x: x["rating"])
    return [_format_professor_response(p) for p in sorted_profs]